[kafka]
brokers = "127.0.0.1:9092"
client_id = "alert-generator"
group_id = "alert"
acks = "all"
linger_ms = 5
compression = "lz4"
# Kafka offset 策略: "earliest" (从最早的消息开始) 或 "latest" (只消费新消息)
auto_offset_reset = "earliest"

[topics]
network_attack = "alerts.network_attack"
malicious_sample = "alerts.malicious_sample"
host_behavior = "alerts.host_behavior"
converged_alerts = "alerts.converged_alerts"

[postgres]
host = "127.0.0.1"
port = 5433
database = "alert_system"
user = "admin"
password = "postgres123"

# 告警类型枚举配置
[alarm_types]

[alarm_types.network_attack]
code = "01"
name = "网络攻击告警"
category = "精控流量"

[alarm_types.network_attack.subtypes]
0 = "IOC 引擎"
1 = "规则引擎"
2 = "杀软阵列"
1001 = "网络扫描探测"
1002 = "网络钓鱼"
1003 = "漏洞利用"
1004 = "后门通信"
1005 = "凭据攻击"
1006 = "拒绝服务"
1007 = "网页篡改"
1008 = "失陷主机"
1009 = "APT攻击"
1010 = "其他网络攻击"

[alarm_types.malicious_sample]
code = "02"
name = "恶意样本告警"
category = "恶意样本"

[alarm_types.malicious_sample.subtypes]
2001 = "计算机病毒"
2002 = "网络蠕虫"
2003 = "特洛伊木马"
2004 = "僵尸网络"
2005 = "勒索软件"
2006 = "挖矿软件"
2007 = "其他恶意样本"

[alarm_types.host_behavior]
code = "03"
name = "主机行为告警"
category = "终端日志"

[alarm_types.host_behavior.subtypes]
3001 = "挖矿攻击"
3002 = "勒索攻击"
3003 = "远控攻击"
3004 = "爆破攻击"
3005 = "后门攻击"
3006 = "注入攻击"
3007 = "横向移动攻击"
3008 = "数据窃取攻击"
3009 = "其它异常行为告警"

