kafka = { brokers = "127.0.0.1:9092", client_id = "alert-generator", group_id = "alert", acks = "all", linger_ms = 5, compression = "lz4" }

[topics]
network_attack = "alerts.network_attack"
malicious_sample = "alerts.malicious_sample"
host_behavior = "alerts.host_behavior"

[postgres]
host = "127.0.0.1"
port = 5433
database = "alert_system"
user = "admin"
password = "postgres123"

# 告警类型枚举配置
[alarm_types]

[alarm_types.network_attack]
code = "01"
name = "网络攻击告警"
category = "精控流量"

[alarm_types.network_attack.subtypes]
"01001" = "网络扫描探测"
"01002" = "网络钓鱼"
"01003" = "漏洞利用"
"01004" = "后门通信"
"01005" = "凭据攻击"
"01006" = "拒绝服务"
"01007" = "网页篡改"
"01008" = "失陷主机"
"01009" = "APT攻击"
"01010" = "其他网络攻击"

[alarm_types.malicious_sample]
code = "02"
name = "恶意样本告警"
category = "恶意样本"

[alarm_types.malicious_sample.subtypes]
"02001" = "计算机病毒"
"02002" = "网络蠕虫"
"02003" = "特洛伊木马"
"02004" = "僵尸网络"
"02005" = "勒索软件"
"02006" = "挖矿软件"
"02007" = "其他恶意样本"

[alarm_types.host_behavior]
code = "03"
name = "主机行为告警"
category = "终端日志"

[alarm_types.host_behavior.subtypes]
"03001" = "挖矿攻击"
"03002" = "勒索攻击"
"03003" = "远控攻击"
"03004" = "爆破攻击"
"03005" = "后门攻击"
"03006" = "注入攻击"
"03007" = "横向移动攻击"
"03008" = "数据窃取攻击"
"03009" = "其它异常行为告警"

