services:
  # 告警系统服务
  alert-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: alert-server:latest
    container_name: alert-server
    network_mode: host
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./config.toml:/app/config.toml:ro
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: 1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s